#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Linting and checking your project before committing'

# Check oxlint Standards
npm run lint ||
(
        echo '😤🏀👋😤 Get that weak s**t out of here! 😤🏀👋😤 
                Linter Check Failed. Make the required changes listed above, add changes and try to commit again.'
        false; 
)